// Code generated by scripts/wire-gen. DO NOT EDIT.
//
// Source: internal/core/wire/events.go
// To regenerate: go run ./scripts/wire-gen > sdk/packages/anvil-client/src/schema.generated.ts

/** Canonical event types — generated from Go. */
export const GENERATED_EVENT_TYPES = [
  "answer.chunk",
  "answer.end",
  "anvil.dropped",
  "checkpoint",
  "done",
  "error",
  "frontend.call",
  "paused",
  "plan.set",
  "plan.step",
  "ready",
  "session.start",
  "sources.found",
  "subagent.end",
  "subagent.start",
  "think.chunk",
  "think.end",
  "think.start",
  "tool.call",
  "tool.result",
] as const;

/** Generated payload interfaces — DO NOT EDIT BY HAND. */

export interface SessionStartPayload {
  task: string;
  threadId: string;
  focus?: string;
}

export interface ThinkStartPayload {
  stepIndex: number;
}

export interface ThinkChunkPayload {
  delta: string;
}

export interface ThinkEndPayload {
  text: string;
  tokens?: ThinkChunkTokens | null;
}

export interface ThinkChunkTokens {
  input?: number | null;
  output?: number | null;
}

export interface AnswerChunkPayload {
  delta: string;
}

export interface AnswerEndPayload {
  text: string;
}

export interface SubQuery {
  id: string;
  query: string;
  intent: string;
  source?: string;
  year?: number | null;
  dependsOn?: string[];
}

export interface PlanObject {
  reason?: string;
  synthesizeHint?: string;
  needsSearch?: boolean | null;
  subQueries: SubQuery[];
}

export interface PlanStep {
  id: string;
  intent: string;
  detail?: string;
  status: string;
  tool?: string;
  index: number;
}

export interface PlanSetPayload {
  plan: PlanObject;
}

export interface PlanStepPayload {
  step: PlanStep;
}

export interface AgentSource {
  id: number;
  url: string;
  title: string;
  domain: string;
}

export interface SourcesFoundPayload {
  sources: AgentSource[];
}

export interface ToolCallPayload {
  name: string;
  input: unknown;
  callId?: string;
}

export interface ToolResultPayload {
  name: string;
  callId?: string;
  result: unknown;
  error?: string;
}

export interface FrontendCallPayload {
  name: string;
  input: unknown;
  callId: string;
}

export interface SubagentStartPayload {
  subId: string;
  role: string;
  task: string;
}

export interface SubagentEndPayload {
  subId: string;
  output: unknown;
}

export interface CheckpointPayload {
  step: number;
}

export interface AnvilDroppedPayload {
  count: number;
  lastId: number;
}

export interface ErrorPayload {
  message: string;
  code?: string;
  severity?: string;
  recoverable?: boolean | null;
  retryable?: boolean | null;
  step_id?: string;
  raw?: unknown;
}

export interface DonePayload {
  answer?: string;
  sources?: AgentSource[];
  related?: string[];
  plan?: PlanObject | null;
  reason?: string;
  steps?: number | null;
}

export interface PausedPayload {
  reason: string;
  resumeAt?: string;
}

export interface ReadyPayload {
  sessionId: string;
  resumeFromId?: number | null;
}

