// Command wire-gen emits a TypeScript schema fragment from the
// canonical Go wire schema in internal/core/wire/events.go.
//
// Usage:
//   go run ./scripts/wire-gen > sdk/packages/anvil-client/src/schema.generated.ts
//
// The emitted fragment contains:
//   - EVENT_TYPES array (single source of truth for the discriminator)
//   - Payload interfaces (one per Payload struct in the Go file)
//
// The generated file is meant to be imported by schema.ts — it does
// not REPLACE schema.ts because schema.ts contains runtime guards
// (isEvent, fromWire, etc) that aren't derivable from Go types.
//
// To add a new event type: edit internal/core/wire/events.go, then
// re-run this generator. Compare the diff in schema.generated.ts
// and merge into schema.ts by hand.
//
// This tool uses only the Go standard library — `go/parser` and
// `go/ast` — to avoid external dependencies.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

func main() {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "internal/core/wire/events.go", nil, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse error: %v\n", err)
		os.Exit(1)
	}

	out := &strings.Builder{}
	fmt.Fprintln(out, "// Code generated by scripts/wire-gen. DO NOT EDIT.")
	fmt.Fprintln(out, "//")
	fmt.Fprintln(out, "// Source: internal/core/wire/events.go")
	fmt.Fprintln(out, "// To regenerate: go run ./scripts/wire-gen > sdk/packages/anvil-client/src/schema.generated.ts")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "/** Canonical event types — generated from Go. */")
	fmt.Fprintln(out, "export const GENERATED_EVENT_TYPES = [")

	// Pass 1: find the EventType const block (the discriminator literals).
	eventTypes := extractEventTypes(file)
	for _, t := range eventTypes {
		fmt.Fprintf(out, "  %q,\n", t)
	}
	fmt.Fprintln(out, "] as const;")
	fmt.Fprintln(out, "")

	// Pass 2: walk the AST and emit TS interfaces for each Payload struct.
	fmt.Fprintln(out, "/** Generated payload interfaces — DO NOT EDIT BY HAND. */")
	fmt.Fprintln(out, "")
	emitted := map[string]bool{}
	ast.Inspect(file, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}
		st, ok := ts.Type.(*ast.StructType)
		if !ok {
			return true
		}
		name := ts.Name.Name
		// Only emit types that are referenced from at least one payload
		// (recursively) or that ARE payloads. Heuristic: emit any struct
		// that's directly used. Top-level filter: skip if neither a
		// payload nor a referenced struct.
		if !isEmittableType(name) {
			return true
		}
		// Skip the Event struct itself — its shape is hand-written in
		// the TS schema (it has the discriminated union pattern that
		// Go can't express). The Payload structs ARE what we emit.
		if name == "Event" {
			return true
		}
		if emitted[name] {
			return true
		}
		emitted[name] = true

		fmt.Fprintf(out, "export interface %s {\n", name)
		for _, field := range st.Fields.List {
			if len(field.Names) == 0 {
				// Embedded — skip for now
				continue
			}
			jsonTag := extractJSONTag(field)
			if jsonTag == "-" {
				continue
			}
			_, jsonName, optional := parseJSONTag(jsonTag)
			fieldName := field.Names[0].Name
			if jsonName == "" {
				jsonName = toCamelCase(fieldName)
			}
			comment := strings.TrimSpace(field.Doc.Text())
			if comment != "" {
				comment = strings.ReplaceAll(comment, "\n", " ")
				fmt.Fprintf(out, "  /** %s */\n", comment)
			}
			mark := ""
			if optional {
				mark = "?"
			}
			tsType := goTypeToTS(field.Type)
			fmt.Fprintf(out, "  %s%s: %s;\n", jsonName, mark, tsType)
		}
		fmt.Fprintln(out, "}")
		fmt.Fprintln(out, "")
		return true
	})

	fmt.Fprint(os.Stdout, out.String())
}

// isEmittableType returns true if the named type should be emitted as
// a TS interface. Conservative: emit anything that's a Payload or a
// struct referenced by another emitted type.
func isEmittableType(name string) bool {
	if strings.HasSuffix(name, "Payload") {
		return true
	}
	switch name {
	case "Event", "PlanStep", "PlanObject", "AgentSource", "SubQuery", "ThinkChunkTokens":
		return true
	}
	return false
}

// extractEventTypes walks the file's decls and pulls the EventType
// constants in declaration order.
func extractEventTypes(file *ast.File) []string {
	var out []string
	for _, decl := range file.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.CONST {
			continue
		}
		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			if len(vs.Values) != 1 {
				continue
			}
			bl, ok := vs.Values[0].(*ast.BasicLit)
			if !ok || bl.Kind != token.STRING {
				continue
			}
			val := strings.Trim(bl.Value, `"`)
			// Only include Event<Name> constants (e.g. EventSessionStart).
			if !strings.HasPrefix(vs.Names[0].Name, "Event") {
				continue
			}
			// Skip meta-constants like EventType (the type name itself).
			if val == "" || len(val) > 64 {
				continue
			}
			out = append(out, val)
		}
	}
	sort.Strings(out)
	return out
}

// extractJSONTag returns the json tag value (without omitempty) or "" if absent.
func extractJSONTag(field *ast.Field) string {
	if field.Tag == nil {
		return ""
	}
	// Tags look like: `json:"name,omitempty"` — strip the backticks,
	// the leading "json:" prefix, and the surrounding double-quotes.
	raw := strings.Trim(field.Tag.Value, "`")
	if !strings.HasPrefix(raw, "json:") {
		return ""
	}
	raw = strings.TrimPrefix(raw, "json:")
	raw = strings.Trim(raw, `"`)
	return raw
}

// parseJSONTag extracts (name, json-name, is-optional) from a json tag
// string. Returns ("", "", false) if the tag is empty.
func parseJSONTag(tag string) (goName string, jsonName string, optional bool) {
	if tag == "" {
		return
	}
	parts := strings.Split(tag, ",")
	jsonName = parts[0]
	for _, p := range parts[1:] {
		if p == "omitempty" {
			optional = true
		}
	}
	return
}

// goTypeToTS converts a Go AST type expression to a TS type string.
// Supports the subset used in events.go. Falls back to "unknown" for
// anything we don't recognize — better to flag than to silently drift.
func goTypeToTS(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return "string"
		case "int", "int32", "int64", "uint", "uint32", "uint64":
			return "number"
		case "bool":
			return "boolean"
		case "float32", "float64":
			return "number"
		case "any", "interface{}":
			return "unknown"
		default:
			// Probably a struct reference (SubQuery, PlanStep, etc).
			return t.Name
		}
	case *ast.StarExpr:
		return goTypeToTS(t.X) + " | null"
	case *ast.ArrayType:
		return goTypeToTS(t.Elt) + "[]"
	case *ast.MapType:
		return "{ [key: string]: " + goTypeToTS(t.Value) + " }"
	case *ast.SelectorExpr:
		// e.g. time.Time — represent as string.
		return "string"
	default:
		return "unknown"
	}
}

func toCamelCase(s string) string {
	// Convert Go field name (PascalCase) to camelCase JSON name.
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}